"""Approved initial source catalog for registry seeding (E2.3)."""

from datetime import timedelta

from naijaledger.sources.models import SourceCreate

SEED_ADDED_BY = "seed:e2.3"
SEED_APPROVED_BY = "human:decision-brief-2026-07-07"

_FEDERAL_SOURCES: list[SourceCreate] = [
    SourceCreate(
        name="Nigeria Open Contracting Portal (NOCOPO)",
        jurisdiction="federal",
        category="procurement",
        url="https://nocopo.bpp.gov.ng/",
        fetch_method="http",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Open Treasury Portal",
        jurisdiction="federal",
        category="payments",
        url="https://opentreasury.gov.ng/",
        fetch_method="http",
        format="html",
        expected_cadence=timedelta(days=1),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Budget Office of the Federation",
        jurisdiction="federal",
        category="budget",
        url="https://budgetoffice.gov.ng/",
        fetch_method="http",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="NEITI",
        jurisdiction="federal",
        category="other",
        url="https://neiti.gov.ng/",
        fetch_method="http",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="OpenStates.ng",
        jurisdiction="federal",
        category="other",
        url="https://openstates.ng/",
        fetch_method="http",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="CAC Beneficial Ownership Register",
        jurisdiction="federal",
        category="company",
        url="https://bor.cac.gov.ng/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=30),
        added_by=SEED_ADDED_BY,
    ),
]

_STATE_PROCUREMENT_SOURCES: list[SourceCreate] = [
    SourceCreate(
        name="Lagos State Open Contracting Portal",
        jurisdiction="state",
        region="Lagos",
        category="procurement",
        url="https://lagosppaocds.azurewebsites.net/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Kaduna State Open Contracting Portal",
        jurisdiction="state",
        region="Kaduna",
        category="procurement",
        url="https://www.ocds.kdsg.gov.ng/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Ekiti State Open Contracting Portal",
        jurisdiction="state",
        region="Ekiti",
        category="procurement",
        url="https://ekitibppaocds.azurewebsites.net/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Adamawa State Open Contracting Portal",
        jurisdiction="state",
        region="Adamawa",
        category="procurement",
        url="https://adamawappaocds.azurewebsites.net/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Ondo State Open Contracting Portal",
        jurisdiction="state",
        region="Ondo",
        category="procurement",
        url="https://ondobppaocds.azurewebsites.net/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Osun State Open Contracting Portal",
        jurisdiction="state",
        region="Osun",
        category="procurement",
        url="https://osunbppaocds.azurewebsites.net/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Anambra State Open Contracting Portal",
        jurisdiction="state",
        region="Anambra",
        category="procurement",
        url="https://anambrappaocds.azurewebsites.net/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
    SourceCreate(
        name="Rivers State Open Contracting Portal",
        jurisdiction="state",
        region="Rivers",
        category="procurement",
        url="https://riversbppaocds.azurewebsites.net/",
        fetch_method="scrapling",
        format="html",
        expected_cadence=timedelta(days=7),
        added_by=SEED_ADDED_BY,
    ),
]

SEED_CATALOG: list[SourceCreate] = _FEDERAL_SOURCES + _STATE_PROCUREMENT_SOURCES
